@baseUrl = http://localhost:3333

### AppController
# @name AppControllerGet
GET {{baseUrl}}/

### AutomaticConceptsController
# @name AutomaticConceptsControllerGet
GET {{baseUrl}}/automatic-concepts

###
# @name MessagesController
### Find all messages
GET {{baseUrl}}/messages
//?limit=10&offset=10

### Find one messages
GET {{baseUrl}}/messages/2

### Create messages
Post {{baseUrl}}/messages
Content-Type: application/json

{
  "text": "Hello, this is a test",
  "from": "Johnny Nuevo",
  "to": "Jane Bravo"
}

### Update messages
PATCH {{baseUrl}}/messages/2
Content-Type: application/json

{
  "text": "Hello, TestNovo",
  "from": "Johnny Bravaaao"
}

### Delete messages
DELETE {{baseUrl}}/messages/5







### PeopleController
# @name PeopleControllerGet
GET {{baseUrl}}/people
//?limit=10&offset=10
### Find one people
GET {{baseUrl}}/people/2

### Create Person
Post {{baseUrl}}/people
Content-Type: application/json

{
  "email": "exemplo3@gmail.com",
  "password": "123456789",
  "name": "Fernando"
}

### Update messages
PATCH {{baseUrl}}/people/12
Content-Type: application/json

{
  "email": "exemplo113@gmail.com",
  "name": "Joaquim"
}

### Delete people
DELETE {{baseUrl}}/people/8
