@baseUrl = http://localhost:3333

### AppController
# @name AppControllerGet
GET {{baseUrl}}/

### AutomaticConceptsController
# @name AutomaticConceptsControllerGet
GET {{baseUrl}}/automatic-concepts

###
# @name AppControllerGetExample
GET {{baseUrl}}/messages

###
GET {{baseUrl}}/messages/1

###
Post {{baseUrl}}/messages
Content-Type: application/json

{
  "messages": "Hello World this is a messages."
}