@baseUrl = http://localhost:3333

### AppController
# @name AppControllerGet
GET {{baseUrl}}/

### AutomaticConceptsController
# @name AutomaticConceptsControllerGet
GET {{baseUrl}}/automatic-concepts

###
# @name MessagesController
### Find all messages
GET {{baseUrl}}/messages/
//?limit=10&offset=10

### Find one messages
GET {{baseUrl}}/messages/1

### Create messages
Post {{baseUrl}}/messages
Content-Type: application/json

{
  "text": "New message",
  "from": "Johnny Bravo",
  "to": "Jane Bravo",
  "read": false,
  "data": "2024-12-10T23:27:47.751Z"
}

### Update messages
PATCH {{baseUrl}}/messages/2
Content-Type: application/json

{
  "text": "Update message!!!",
  "from": "Johnny Bravo",
  "to": "Jane Bravo",
  "read": false,
  "data": "2024-12-10T23:27:47.751Z"
}

### Delete messages
DELETE {{baseUrl}}/messages/2